Repository brunowf/Cezin, pull requests merged in 2019-11, with the labels that each got.

#1 arrumando main
  main.c
Labels: enhancement

#2 Bruno repl
  README.md
  helpinho.h
  main.c
Labels: Master, bug, documentation, enhancement

#3 Bruno
  README.md
Labels: documentation, enhancement

#4 Bruno
  README.md
  helpinho.h
  main.c
Labels: documentation, enhancement
